### ISSUE TITLE
Where do i get bread

### ISSUE THREAD

**Issue by alexanderkoumis** [ariskoumis/munch#3]
Is this the kitchen?

**Comment by ariskoumis** [comment]
Hello Alexander,

After further review of your question, we here at Munch acknowledge that this is a crucial error in Munch: we didn't tell you where to get bread. Your profile location states that you're in San Jose, so we've researched out every grocery store in the San Jose area which sells bread. [Here is that list.](https://www.youtube.com/watch?v=dQw4w9WgXcQ)  We wish you all the best!

Munch On!
Aris Koumis, Munch
